// Generated by MiniCompiler - Huguini79

int main() {
    char* cadenaDeTexto = "EstoEsMiLenguajeDeProgramacion";
    int numero = 10;
    float numeroFloat = 10000000000;
    numero++;
    numero++;
    numero++;
    return numero;
}
