#ifndef PARSER_H
#define PARSER_H

#include <iostream>
#include <string>
#include <vector>
#include <fstream>

#include "../lexer/lexer.hpp"

void process(std::vector<Token> &tokens) {
    std::ofstream Compilado("compiled.c");
    Compilado << "// Generated by MiniCompiler - Huguini79" << std::endl << std::endl;
    Compilado << "int main() {" << std::endl;
    for (int i = 0; i < tokens.size(); ++i) {
        if (tokens[0].lexema == "return" && tokens[0].tipo_de_token == TokenType::Keyword) {
            if (tokens[1].tipo_de_token == TokenType::Number) {
                Compilado << "    return " << tokens[1].lexema << ";";
                break;
            }
        }
    }
    Compilado << std::endl << "}";
}

#endif